Feature/book adder
smichaelshal/digitalib pull request #6
Opened 2024-08-15 12:15 UTC by smichaelshal

2024-08-17 17:10 UTC, Iris2534 commented on src/main/java/org/plasma/digitalib/adders/StorageBookAdder.java
> +    private final Function<Book, Boolean> bookIdentifierFilter;
There's a special type for a Function that returns a boolean

2024-08-17 17:11 UTC, Iris2534 commented on src/main/java/org/plasma/digitalib/adders/StorageBookAdder.java
> +    private final Function<Book, Boolean> bookIdentifierFilter;
How is this injected? The book's details change per call of `add`

2024-08-17 17:12 UTC, Iris2534 commented on src/main/java/org/plasma/digitalib/adders/StorageBookAdder.java
> +                    || !bookResult.getGenre().equals(book.getGenre())) {
What if `book` is a new copy of an existing book? Then, wouldn't his summary be empty but `bookResult`'s summary won't be?

2024-08-17 17:13 UTC, Iris2534 commented on src/main/java/org/plasma/digitalib/adders/StorageBookAdder.java
> +        return this.storage.create(book);
Add a blank line

2024-08-17 17:13 UTC, Iris2534 commented on src/main/java/org/plasma/digitalib/adders/StorageBookAdder.java
> +public class StorageBookAdder implements ItemAdder<Book> {
Add logs

2024-08-17 17:16 UTC, Iris2534 commented on src/main/java/org/plasma/digitalib/filters/BookIdentifierFilter.java
> +                .equals(this.expectedBookIdentifier.getAuthor());
Overriding `equals` in `BookIdentifier` will make this code much more simple. Moreover, when adding more fields to `BookIdentifier` the developers will have to remember to add the equality check here...

2024-08-17 17:16 UTC, Iris2534 commented on src/main/java/org/plasma/digitalib/filters/BookIdentifierFilter.java
> +public class BookIdentifierFilter implements Function<Book, Boolean> {
Add tests for this class

2024-08-17 17:16 UTC, Iris2534 commented on src/main/java/org/plasma/digitalib/filters/BookIdentifierFilter.java
> +public class BookIdentifierFilter implements Function<Book, Boolean> {
Add logs

2024-08-17 17:17 UTC, Iris2534 commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +
Redundant blank line

2024-08-17 17:17 UTC, Iris2534 commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +
Redundant blank line

2024-08-17 17:17 UTC, Iris2534 commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +
Redundant blank line

2024-08-17 17:22 UTC, Iris2534 commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +    public void add_withTwoBooksWithDifferentAuthor_should_returnTrue() {
Verify that the storage was called as well

2024-08-18 06:16 UTC, ofermayo requested changes

2024-08-18 06:16 UTC, ofermayo commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +        this.storageBookAdder.add(this.book);
This should be part of the "Arrange" clause.

2024-08-18 06:16 UTC, ofermayo commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +        this.storageBookAdder.add(this.book);
This should be part of the "Arrange" clause.

2024-08-18 06:16 UTC, ofermayo commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +
Redundant blank line.

2024-08-18 06:16 UTC, ofermayo commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +import java.time.Instant;
Rearrange the imports in a way that first you will have all the non static standard library imports ordered alphabetically, then a blank line, then all other non static imports ordered alphabetically,  then a blank line, then all static standard library imports ordered alphabetically, then blank line, then all  other static imports ordered alphabetically.
This is not part of the official java code convention, but it makes the i.ports easy to understand and helps to find specific imports amoung them.

2024-08-18 09:58 UTC, smichaelshal commented on src/main/java/org/plasma/digitalib/adders/StorageBookAdder.java
> +    private final Function<Book, Boolean> bookIdentifierFilter;
this is filter pass to storage, if you mean Predicate then the change should be in storage because it is not implement a Function and has test instead of apply which storage uses.
Make the change in storage?

2024-08-18 09:58 UTC, smichaelshal commented on src/main/java/org/plasma/digitalib/adders/StorageBookAdder.java
> +    private final Function<Book, Boolean> bookIdentifierFilter;
fix

2024-08-18 09:58 UTC, smichaelshal commented on src/main/java/org/plasma/digitalib/adders/StorageBookAdder.java
> +                    || !bookResult.getGenre().equals(book.getGenre())) {
fix

2024-08-18 09:58 UTC, smichaelshal commented on src/main/java/org/plasma/digitalib/adders/StorageBookAdder.java
> +        return this.storage.create(book);
fix

2024-08-18 09:58 UTC, smichaelshal commented on src/main/java/org/plasma/digitalib/adders/StorageBookAdder.java
> +public class StorageBookAdder implements ItemAdder<Book> {
fix

2024-08-18 09:58 UTC, smichaelshal commented on src/main/java/org/plasma/digitalib/filters/BookIdentifierFilter.java
> +public class BookIdentifierFilter implements Function<Book, Boolean> {
fix

2024-08-18 09:59 UTC, smichaelshal commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +
fix

2024-08-18 09:59 UTC, smichaelshal commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +        this.storageBookAdder.add(this.book);
fix

2024-08-18 09:59 UTC, smichaelshal commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +
fix

2024-08-18 09:59 UTC, smichaelshal commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +import java.time.Instant;
fix

2024-08-18 09:59 UTC, smichaelshal commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +        this.storageBookAdder.add(this.book);
fix

2024-08-18 09:59 UTC, smichaelshal commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +    public void add_withTwoBooksWithDifferentAuthor_should_returnTrue() {
Do you mean without mock?

2024-08-18 10:00 UTC, smichaelshal commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +
fix

2024-08-19 12:18 UTC, Iris2534 commented on src/main/java/org/plasma/digitalib/adders/StorageBookAdder.java
> +                        new BookIdentifierFilter(book.getBookIdentifier()));
Move it to the line upwards.

2024-08-19 12:19 UTC, Iris2534 commented on src/main/java/org/plasma/digitalib/adders/StorageBookAdder.java
> +    private final Function<Book, Boolean> bookIdentifierFilter;
Fix it as we already discussed

2024-08-20 08:51 UTC, Iris2534 commented on src/main/java/org/plasma/digitalib/adders/StorageBookAdder.java
> +        log.debug("try add {} to storage", book);
Have you happened to succeed? give more information.

2024-08-20 08:53 UTC, Iris2534 commented on src/main/java/org/plasma/digitalib/filters/BookIdentifierFilter.java
> +                "id: {}, name: {}, Author: {}",
1. You can add the book itself, and not write every field manually.
2. You just wrote a book. what is the purpose of it? what happened to the book? give more context

2024-08-20 08:58 UTC, Iris2534 commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +    public void add_withTwoBooksWithDifferentAuthor_should_returnTrue() {
with mock

2024-08-20 09:00 UTC, Iris2534 commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +    public void add_withNewBook_should_returnTrue() {
There shouldn't be `_` after the should. (change in the rests of the tests as well)

2024-08-20 10:05 UTC, Iris2534 commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +        // Arrange
There is no need to write it twice

2024-08-20 10:06 UTC, Iris2534 commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +        this.storageBookAdder.add(this.book);
should be part of the arrange scope

2024-08-20 10:07 UTC, Iris2534 commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +        this.storageBookAdder.add(this.book);
You did not fix

2024-08-20 10:12 UTC, Iris2534 commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +        this.storage = mock(Storage.class);
Use `@Mock` and `MocitoJunitRunner` class

2024-08-20 10:17 UTC, Iris2534 commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +        when(this.storage.readAll(any(Predicate.class))).thenReturn(this.books);
You can use only `any()`. The method can receive only `Predicate`, you won't be able to call it with something else (change in other tests as well).

2024-08-20 10:18 UTC, Iris2534 commented on src/test/java/org/plasma/digitalib/filters/BookIdentifierFilterTest.java
> +    void test_withDifferentAuthors_shouldReturnTrue() {
It should return false

2024-08-20 13:48 UTC, smichaelshal commented on src/main/java/org/plasma/digitalib/adders/StorageBookAdder.java
> +    private final Function<Book, Boolean> bookIdentifierFilter;
fix

2024-08-20 13:52 UTC, smichaelshal commented on src/main/java/org/plasma/digitalib/filters/BookIdentifierFilter.java
> +                .equals(this.expectedBookIdentifier.getAuthor());
fix

2024-08-20 13:56 UTC, smichaelshal commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +    public void add_withTwoBooksWithDifferentAuthor_should_returnTrue() {
Which department to mock? to the books?

2024-08-20 13:57 UTC, smichaelshal commented on src/main/java/org/plasma/digitalib/adders/StorageBookAdder.java
> +                        new BookIdentifierFilter(book.getBookIdentifier()));
fix

2024-08-20 14:01 UTC, smichaelshal commented on src/main/java/org/plasma/digitalib/adders/StorageBookAdder.java
> +        log.debug("try add {} to storage", book);
fix

2024-08-20 14:07 UTC, smichaelshal commented on src/main/java/org/plasma/digitalib/filters/BookIdentifierFilter.java
> +                "id: {}, name: {}, Author: {}",
fix 1

I didn't understand the intention of 2, the filter didn't write a book and it doesn't really have a context to display.

Was it intended that I present in debug the result of the comparison between the book from the parameter and the injected book?

2024-08-20 14:08 UTC, smichaelshal commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +    public void add_withNewBook_should_returnTrue() {
fix

2024-08-20 14:15 UTC, smichaelshal commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +        this.storageBookAdder.add(this.book);
But that's the point of these tests, isn't it?
And if I have to remove it then Act remains empty?

2024-08-20 14:21 UTC, smichaelshal commented on src/test/java/org/plasma/digitalib/filters/BookIdentifierFilterTest.java
> +    void test_withDifferentAuthors_shouldReturnTrue() {
fix

2024-08-21 08:59 UTC, smichaelshal commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +        this.storage = mock(Storage.class);
fix

2024-08-22 08:51 UTC, Iris2534 commented on src/test/java/org/plasma/digitalib/filters/BookIdentifierFilterTest.java
> +    void test_withDifferentAuthors_shouldReturnTrue() {
You did not.

2024-08-22 08:56 UTC, Iris2534 commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +    private Predicate<Book> bookIdentifierFilter;
redundant field

2024-08-22 09:00 UTC, Iris2534 commented on src/main/java/org/plasma/digitalib/filters/BookIdentifierFilter.java
> +                "id: {}, name: {}, Author: {}",
You wrote just the book. You did not write any information about the book. 
You did not even write that it was filtered or passed the filter. 
It is a useless log this way, add more information

2024-08-22 10:09 UTC, smichaelshal commented on src/main/java/org/plasma/digitalib/filters/BookIdentifierFilter.java
> +                "id: {}, name: {}, Author: {}",
fix

2024-08-22 10:11 UTC, smichaelshal commented on src/test/java/org/plasma/digitalib/filters/BookIdentifierFilterTest.java
> +    void test_withDifferentAuthors_shouldReturnTrue() {
fix

2024-08-22 10:14 UTC, smichaelshal commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +    private Predicate<Book> bookIdentifierFilter;
fix

2024-08-26 12:34 UTC, Iris2534 commented on src/main/java/org/plasma/digitalib/filters/BookIdentifierFilter.java
> +        log.debug("The book are {}match to filter"
add space between `{}` and `match`

2024-08-26 12:38 UTC, Iris2534 commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +package org.plasma.digitalib.adders;
What about testing the logic? You only tested the return value. 
What if the value was not added to the storage?

2024-08-26 12:42 UTC, Iris2534 commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +                new LinkedList());
Read the intelij warning!!!
Don't ignore Intelij warnings
fix in other tests as well

2024-08-27 06:57 UTC, smichaelshal commented on src/main/java/org/plasma/digitalib/filters/BookIdentifierFilter.java
> +        log.debug("The book are {}match to filter"
This is on purpose because in case the `filterResult` is false then I don't want to add anything and then there will be unnecessary space

2024-08-27 07:01 UTC, smichaelshal commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +                new LinkedList());
fix

2024-08-27 07:38 UTC, smichaelshal commented on src/test/java/org/plasma/digitalib/adders/StorageBookAdderTest.java
> +package org.plasma.digitalib.adders;
fix

2024-08-28 11:48 UTC, Iris2534 commented
approved

2024-08-29 10:38 UTC, merged